<?php

define("DB_HOST", "");
define("DB_USER", "root");
define("DB_PASSWORD", "");
define("DB_NAME", "kingdoms");
define("BOT_TOKEN", "MjEwNzY4MTIyNTY5ODE4MTEy.CoTkuw.zgAhNyJbyMO90zvq_T1bH_guOYc");

define('ADMIN1', '108380352791187456');
define('ADMIN2', '210768122569818112');

define('AUTHORIZEDBOT', '108380352791187456');

define('START_GOLD', 500);
define('START_IRON', 20);
define('START_FOOD', 140);
define('START_POPULATION', 10);
define('START_SOLDIERS', 5);
define('START_HOUSES', 5);
define('START_FARMS', 2);
define('START_DAMS', 1);
define('START_BATTLEMENTS', 10);
define('START_STONE', 10);
define('START_WOOD', 100);

define('LAND_PER_KINGDOM', 250);
define('COST_TO_ANNEX', 500);
define('MAP_SIZE', 100);

define('ROUND_GOLD', 10);
define('ROUND_GOLD_PER_BANK', 10);
define('FOOD_PER_FARM', 10);
define('FOOD_CONSUMED_PER_HEAD_POPULATION', 1);
define('WATER_CONSUMED_PER_HEAD_POPULATION', 10);
define('ROUND_IRON_PER_MINE', 5);
define('ROUND_WEAPON_PER_FACTORY', 5);
define('ROUND_SOLDIERS_PER_BARRACKS', 2);
define('MAGIC_PER_PRIESTHOOD', 5);
define('PEOPLE_PER_HOUSE', 4);
define('POPULATIO_NREPRODUCTION_RATE', 0.3);
define('SOLDIERS_PER_BARRACKS', 10);
define('INCOME_PER_FOREST', 1);
define('FOOD_PER_FOREST', 1);
define('HOME_TURF_ADVANTAGE', 10);
define('WATER_PER_DAM', 300);
define('WATER_DAM_LIMIT', 1000);
define('STONE_PER_QUARRY', 2);
define('HORSES_PER_STABLE', 5);
define('HORSE_REPRODUCTION_RATE', 1);
define('TECHNICAL_INSTITUTE_ADVANTAGE_RATE', 0.95);
define('WOOD_PER_FOREST', 15);
define('PEOPLE_PER_LANDSQUARE_FOR_ANNEXATION', 20);